[package]
name = "myopic"
version = "0.1.0"
authors = ["Tom <tomoliverball@gmail.com>"]
edition = "2018"

#[lib]
##crate-type = ["cdylib", "rlib"]

#[features]
#default = ["console_error_panic_hook"]

[dependencies]
# wasm-bindgen = "0.2"
itertools = "0.8"
lazy_static = "1.2.0"
rand = "0.6.5"
rand_pcg = "0.1.2"

