[package]
name = "myopic-brain"
version = "0.1.0"
authors = ["Thomas Ball <tomoliverball@gmail.com>"]
edition = "2018"

[dependencies]
myopic-core = "1.0.1"
myopic-board = "1.0.0"
lazy_static = "1.4.0"
itertools = "0.9.0"
regex = "1"
